services:
  dayz-signal-server1:
    environment:
      API_KEY: ""
      API_KEY_FILE: /run/secrets/server1_api_key
      RCON_PASSWORD: ""
      RCON_PASSWORD_FILE: /run/secrets/server1_rcon_password
    secrets:
      - server1_api_key
      - server1_rcon_password

  dayz-signal-server2:
    environment:
      API_KEY: ""
      API_KEY_FILE: /run/secrets/server2_api_key
      RCON_PASSWORD: ""
      RCON_PASSWORD_FILE: /run/secrets/server2_rcon_password
    secrets:
      - server2_api_key
      - server2_rcon_password

secrets:
  server1_api_key:
    file: ./.secrets/server1_api_key.txt
  server1_rcon_password:
    file: ./.secrets/server1_rcon_password.txt
  server2_api_key:
    file: ./.secrets/server2_api_key.txt
  server2_rcon_password:
    file: ./.secrets/server2_rcon_password.txt
